# Generated by Django 4.1.7 on 2023-03-25 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(blank=True, default='Batch<built-in function id>', max_length=500, null=True)),
                ('date_created', models.DateField(default=datetime.date.today, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('kg', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('date', models.DateField(default=datetime.date.today, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sales',
                'ordering': ['-date'],
            },
        ),
    ]
