# Generated by Django 4.1.7 on 2023-03-25 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GasApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch', to='GasApp.batch'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_name',
            field=models.CharField(blank=True, default='Batch', max_length=500, null=True),
        ),
    ]
