# Generated by Django 4.1.7 on 2023-03-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasApp', '0002_sale_batch_alter_batch_batch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='close_account',
            field=models.BooleanField(default=False),
        ),
    ]
