# Generated by Django 4.1.7 on 2023-03-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasApp', '0003_batch_close_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_name',
            field=models.CharField(blank=True, default='Batch', max_length=500, null=True, unique=True),
        ),
    ]
