# Generated by Django 4.1.7 on 2023-03-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasApp', '0004_alter_batch_batch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='vendor_phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
