# Generated by Django 4.1.7 on 2023-04-02 14:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GasApp', '0005_batch_vendor_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, default='Batch', max_length=500, null=True, unique=True)),
                ('date_created', models.DateField(default=datetime.date.today, null=True)),
                ('location', models.CharField(blank=True, default='Shop', max_length=500, null=True)),
                ('shop_manager', models.CharField(blank=True, max_length=500, null=True)),
                ('manager_phone', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['shop_name', '-date_created'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop', to='GasApp.shop'),
        ),
    ]
