# Generated by Django 4.1.7 on 2023-04-02 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GasApp', '0006_shop_batch_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(blank=True, default='Shop 1', max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
