# Generated by Django 4.1.7 on 2023-04-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GasApp', '0008_alter_batch_price_per_kg_alter_shop_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['shop_name', 'date_created', 'id']},
        ),
    ]
