# Generated by Django 4.1.7 on 2023-05-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasApp', '0009_alter_shop_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('POS', 'POS'), ('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer')], default='Cash', max_length=100),
        ),
    ]
